import { createSlice } from "@reduxjs/toolkit";

const gtpSlice = createSlice({
  name: "gpt",
  initialState: {
    showGptSearch: false,
    aiMovies: [
      {
        adult: false,
        backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
        genre_ids: [12, 878, 28],
        id: 299534,
        original_language: "en",
        original_title: "Avengers: Endgame",
        overview:
          "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
        popularity: 17.9296,
        poster_path: "/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
        release_date: "2019-04-24",
        title: "Avengers: Endgame",
        video: false,
        vote_average: 8.24,
        vote_count: 26461,
      },
      {
        adult: false,
        backdrop_path: "/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg",
        genre_ids: [12, 28, 878],
        id: 299536,
        original_language: "en",
        original_title: "Avengers: Infinity War",
        overview:
          "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
        popularity: 32.2231,
        poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
        release_date: "2018-04-25",
        title: "Avengers: Infinity War",
        video: false,
        vote_average: 8.2,
        vote_count: 30676,
      },
      {
        adult: false,
        backdrop_path: "/zD5v1E4joAzFvmAEytt7fM3ivyT.jpg",
        genre_ids: [28, 12, 878],
        id: 634649,
        original_language: "en",
        original_title: "Spider-Man: No Way Home",
        overview:
          "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        popularity: 27.9659,
        poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
        release_date: "2021-12-15",
        title: "Spider-Man: No Way Home",
        video: false,
        vote_average: 7.943,
        vote_count: 20858,
      },
      {
        adult: false,
        backdrop_path: "/1RWLMyC9KcFfcaoViMiJGSSZzzr.jpg",
        genre_ids: [28, 12, 878],
        id: 100402,
        original_language: "en",
        original_title: "Captain America: The Winter Soldier",
        overview:
          "After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.",
        popularity: 7.127,
        poster_path: "/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
        release_date: "2014-03-20",
        title: "Captain America: The Winter Soldier",
        video: false,
        vote_average: 7.656,
        vote_count: 19213,
      },
      {
        adult: false,
        backdrop_path: "/uLtVbjvS1O7gXL8lUOwsFOH4man.jpg",
        genre_ids: [28, 878, 12],
        id: 118340,
        original_language: "en",
        original_title: "Guardians of the Galaxy",
        overview:
          "Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.",
        popularity: 7.4926,
        poster_path: "/jPrJPZKJVhvyJ4DmUTrDgmFN0yG.jpg",
        release_date: "2014-07-30",
        title: "Guardians of the Galaxy",
        video: false,
        vote_average: 7.905,
        vote_count: 28629,
      },
      {
        adult: false,
        backdrop_path: "/cyecB7godJ6kNHGONFjUyVN9OX5.jpg",
        genre_ids: [28, 878, 12],
        id: 1726,
        original_language: "en",
        original_title: "Iron Man",
        overview:
          "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
        popularity: 18.4035,
        poster_path: "/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
        release_date: "2008-04-30",
        title: "Iron Man",
        video: false,
        vote_average: 7.652,
        vote_count: 27055,
      },
      {
        adult: false,
        backdrop_path: "/6G2fLCVm9fiLyHvBrccq6GSe2ih.jpg",
        genre_ids: [28, 12, 878],
        id: 284053,
        original_language: "en",
        original_title: "Thor: Ragnarok",
        overview:
          "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of a powerful new threat, the ruthless Hela.",
        popularity: 12.489,
        poster_path: "/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
        release_date: "2017-10-02",
        title: "Thor: Ragnarok",
        video: false,
        vote_average: 7.585,
        vote_count: 21203,
      },
      {
        adult: false,
        backdrop_path: "/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg",
        genre_ids: [28, 12, 878],
        id: 284054,
        original_language: "en",
        original_title: "Black Panther",
        overview:
          "King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.",
        popularity: 13.5288,
        poster_path: "/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
        release_date: "2018-02-13",
        title: "Black Panther",
        video: false,
        vote_average: 7.373,
        vote_count: 22633,
      },
      {
        adult: false,
        backdrop_path: "/3zvZ699gMW2RhWc0GisIukzq0Ls.jpg",
        genre_ids: [28, 12, 14],
        id: 284052,
        original_language: "en",
        original_title: "Doctor Strange",
        overview:
          "After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.",
        popularity: 9.7843,
        poster_path: "/xf8PbyQcR5ucXErmZNzdKR0s8ya.jpg",
        release_date: "2016-10-25",
        title: "Doctor Strange",
        video: false,
        vote_average: 7.419,
        vote_count: 22599,
      },
      {
        adult: false,
        backdrop_path: "/qAzYK4YPSWDc7aa4R43LcwRIAyb.jpg",
        genre_ids: [28, 12, 878],
        id: 299537,
        original_language: "en",
        original_title: "Captain Marvel",
        overview:
          "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.",
        popularity: 7.0273,
        poster_path: "/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
        release_date: "2019-03-06",
        title: "Captain Marvel",
        video: false,
        vote_average: 6.8,
        vote_count: 16106,
      },
      {
        adult: false,
        backdrop_path: "/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
        genre_ids: [878, 28, 12],
        id: 24428,
        original_language: "en",
        original_title: "The Avengers",
        overview:
          "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
        popularity: 33.6401,
        poster_path: "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
        release_date: "2012-04-25",
        title: "The Avengers",
        video: false,
        vote_average: 7.766,
        vote_count: 32190,
      },
      {
        adult: false,
        backdrop_path: "/1K3JmSNUN8OpjYsCjc0Hy0SYxAb.jpg",
        genre_ids: [878, 28, 12],
        id: 102899,
        original_language: "en",
        original_title: "Ant-Man",
        overview:
          "Armed with the astonishing ability to shrink in scale but increase in strength, master thief Scott Lang must embrace his inner-hero and help his mentor, Doctor Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.",
        popularity: 7.402,
        poster_path: "/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg",
        release_date: "2015-07-14",
        title: "Ant-Man",
        video: false,
        vote_average: 7.07,
        vote_count: 20144,
      },
      {
        adult: false,
        backdrop_path: "/aJn9XeesqsrSLKcHfHP4u5985hn.jpg",
        genre_ids: [878, 12, 28],
        id: 283995,
        original_language: "en",
        original_title: "Guardians of the Galaxy Vol. 2",
        overview:
          "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
        popularity: 13.2664,
        poster_path: "/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg",
        release_date: "2017-04-19",
        title: "Guardians of the Galaxy Vol. 2",
        video: false,
        vote_average: 7.613,
        vote_count: 22056,
      },
      {
        adult: false,
        backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
        genre_ids: [28, 12, 878, 18],
        id: 315635,
        original_language: "en",
        original_title: "Spider-Man: Homecoming",
        overview:
          "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
        popularity: 18.9684,
        poster_path: "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
        release_date: "2017-07-05",
        title: "Spider-Man: Homecoming",
        video: false,
        vote_average: 7.331,
        vote_count: 22278,
      },
      {
        adult: false,
        backdrop_path: "/wdwcOBMkt3zmPQuEMxB3FUtMio2.jpg",
        genre_ids: [12, 28, 878],
        id: 271110,
        original_language: "en",
        original_title: "Captain America: Civil War",
        overview:
          "Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.",
        popularity: 12.4249,
        poster_path: "/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
        release_date: "2016-04-27",
        title: "Captain America: Civil War",
        video: false,
        vote_average: 7.447,
        vote_count: 23203,
      },
      {
        adult: false,
        backdrop_path: "/iVped1djsF0tvGkvnHbzsE3ZPTF.jpg",
        genre_ids: [28, 12, 878],
        id: 68721,
        original_language: "en",
        original_title: "Iron Man 3",
        overview:
          "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
        popularity: 15.1719,
        poster_path: "/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg",
        release_date: "2013-04-18",
        title: "Iron Man 3",
        video: false,
        vote_average: 6.93,
        vote_count: 22627,
      },
      {
        adult: false,
        backdrop_path: "/90seuFwm25GWNbF1ydkaPa4DrdO.jpg",
        genre_ids: [28, 12, 14],
        id: 76338,
        original_language: "en",
        original_title: "Thor: The Dark World",
        overview:
          "Thor fights to restore order across the cosmos… but an ancient race led by the vengeful Malekith returns to plunge the universe back into darkness. Faced with an enemy that even Odin and Asgard cannot withstand, Thor must embark on his most perilous and personal journey yet, one that will reunite him with Jane Foster and force him to sacrifice everything to save us all.",
        popularity: 8.9501,
        poster_path: "/wD6g4EcmR6R3VNbuBmNOVq2qWrM.jpg",
        release_date: "2013-10-30",
        title: "Thor: The Dark World",
        video: false,
        vote_average: 6.516,
        vote_count: 17651,
      },
      {
        adult: false,
        backdrop_path: "/2tcTm5oRlRN5fKFvY4Gbrwp8h38.jpg",
        genre_ids: [28, 12, 878],
        id: 363088,
        original_language: "en",
        original_title: "Ant-Man and the Wasp",
        overview:
          "Just when his time under house arrest is about to end, Scott Lang once again puts his freedom at risk to help Hope van Dyne and Dr. Hank Pym dive into the quantum realm and try to accomplish, against time and any chance of success, a very dangerous rescue mission.",
        popularity: 7.109,
        poster_path: "/cFQEO687n1K6umXbInzocxcnAQz.jpg",
        release_date: "2018-07-04",
        title: "Ant-Man and the Wasp",
        video: false,
        vote_average: 6.917,
        vote_count: 13619,
      },
      {
        adult: false,
        backdrop_path: "/rAksPS6LjBONzY84szQBz5gGej6.jpg",
        genre_ids: [28, 12, 14],
        id: 566525,
        original_language: "en",
        original_title: "Shang-Chi and the Legend of the Ten Rings",
        overview:
          "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
        popularity: 15.4994,
        poster_path: "/d08HqqeBQSwN8i8MEvpsZ8Cb438.jpg",
        release_date: "2021-09-01",
        title: "Shang-Chi and the Legend of the Ten Rings",
        video: false,
        vote_average: 7.522,
        vote_count: 9798,
      },
      {
        adult: false,
        backdrop_path: "/c6H7Z4u73ir3cIoCteuhJh7UCAR.jpg",
        genre_ids: [878, 28, 12],
        id: 524434,
        original_language: "en",
        original_title: "Eternals",
        overview:
          "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.",
        popularity: 9.2891,
        poster_path: "/lFByFSLV5WDJEv3KabbdAF959F2.jpg",
        release_date: "2021-11-03",
        title: "Eternals",
        video: false,
        vote_average: 6.814,
        vote_count: 8619,
      },
    ],
  },
  reducers: {
    toggleGptSearchView: (state) => {
      state.showGptSearch = !state.showGptSearch;
    },
    addAiMoviesResult: (state, action) => {
      // console.log(action.payload,"sfadfdfadfsadf",action.payload.length);
      let data = action.payload
      if(!data.length) data = state.aiMovies; 
      state.aiMovies = data;
    },
    removeAiMoviesResult: (state) => {
      state.aiMovies = null;
    },
  },
});

export const {toggleGptSearchView, addAiMoviesResult, removeAiMoviesResult} = gtpSlice.actions;
export default gtpSlice.reducer;